
image_name := "envoy-extproc-sdk-go"
image_tag := `git rev-parse HEAD`
generated_code := "gen/proto/go"

version := "v0"

update:
    go get -u ./.. && just tidy

tidy:
    for D in $( find . -type d ) ; do go mod tidy ; done

format:
    for D in $( find . -type d ) ; do go fmt $D/*.go ; done

unit-test: 
    echo "TBD"

integration-test: 
    echo "TBD"

coverage: 
    echo "TBD"

run EXAMPLE="noop" *FLAGS="":
    go run {{EXAMPLE}}/*.go {{FLAGS}}

build EXAMPLE="noop" *FLAGS="":
    go build {{EXAMPLE}} {{FLAGS}}

containerize EXAMPLE="noop" *FLAGS="": 
    docker build . \
        -t {{image_name}}-{{EXAMPLE}}:{{image_tag}} \
        --build-arg EXAMPLE={{EXAMPLE}} \
        {{FLAGS}}
