name: Pull Request Checks
on: 
  push:
    branches: 
      - main
  pull_request: {}
jobs:
  build-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'
      - name: Check build(s)
        run: |
          go build ./...
          (cd examples && go build ./...)
          (cd test && go build ./...)
  vet-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'
      - name: Vet the main library
        run: |
          go install golang.org/x/tools/go/analysis/passes/shadow/cmd/shadow@latest
          go vet -vettool=$(go env GOPATH)/bin/shadow ./...
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'
      - name: Start compose setup
        run: docker compose -f test/compose.yaml up --build -d --wait --wait-timeout 90
      - name: Run tests
        working-directory: test
        run: go test -v ./...
      - name: Stop compose setup
        if: always()
        run: docker compose -f test/compose.yaml down --volumes
